### ISSUE TITLE
Atelier Lydie & Suelle ~The Alchemists and the Mysterious Paintings~ .PAK

### ISSUE THREAD

**Issue by makc-ar** [shizukachan/atelier_pak_decrypt#1]
Hi **shizukachan**! Ho about this game http://store.steampowered.com/app/756590/Atelier_Lydie__Suelle_The_Alchemists_and_the_Mysterious_Paintings?
a18_decrypt or a17_decrypt tool can't open PAK file PACK00_04_01.PAK and PACK00_04_03.PAK

**Comment by shizukachan** [comment]
Use a18_decrypt. Ensure you have sufficient disk space or permissions to create the output files.
LGTM. Closing.
